apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-job
  labels:
    app: hello-world
spec:
  backoffLimit: 3   # Allow 3 retries before marking as failed
  ttlSecondsAfterFinished: 300 # Delete Job 5 minutes after it finishes
  template:
    metadata:
      labels:
        job: hello-world
    spec:
      restartPolicy: OnFailure  # Retry container only on failure
      containers:
      - name: hello-world
        image: roeeelnekave/hello-world:latest
        imagePullPolicy: Always # Always pull to ensure fresh version
        resources:
          requests: 
            memory: "64Mi" 
            cpu: "50m" 
          limits:
            memory: "128Mi" 
            cpu: "100m" 
